change quotes to apostrophes
meilisearch/cloud-scripts pull request #60
Opened 2021-10-04 15:36 UTC by viogustian

2021-10-04 15:38 UTC, curquiza requested changes
This change should only applied to literal strings.
Strings where there are interpretation should keep the `"` quote.
Ex: strings with `\em` and string with `$`.

2021-10-05 02:08 UTC, viogustian commented
Ok, i will fix it

2021-10-05 03:56 UTC, viogustian commented
I've fixed it

2021-10-05 07:49 UTC, alallema reviewed
Thanks for this PR @viogustian. I made some suggestions

2021-10-05 07:49 UTC, alallema commented on scripts/deploy-meilisearch.sh
> +git checkout '$1'
```suggestion
git checkout "$1"
```

2021-10-05 07:49 UTC, alallema commented on scripts/deploy-meilisearch.sh
> +sed -i 's/provider_name/$2/' /var/opt/meilisearch/scripts/first-login/000-set-meili-env.sh
```suggestion
sed -i "s/provider_name/$2/" /var/opt/meilisearch/scripts/first-login/000-set-meili-env.sh
```

2021-10-05 07:49 UTC, alallema commented on scripts/first-login/000-set-meili-env.sh
> +            * ) echo '  Please answer by writting 'y' for yes or 'n' for no.';
```suggestion
            * ) echo "  Please answer by writing 'y' for yes or 'n' for no.";
```

2021-10-05 07:49 UTC, alallema commented on scripts/first-login/000-set-meili-env.sh
> +            * ) echo '  Please answer by writting 'y' for yes or 'n' for no.';
```suggestion
            * ) echo "  Please answer by writing 'y' for yes or 'n' for no.";
```

2021-10-05 07:49 UTC, alallema commented on scripts/first-login/000-set-meili-env.sh
> +            * ) echo '  Please answer by writting 'y' for yes or 'n' for no.';
```suggestion
            * ) echo "  Please answer by writing 'y' for yes or 'n' for no.";
```

2021-10-05 07:49 UTC, alallema commented on scripts/first-login/000-set-meili-env.sh
> +            * ) echo '  Please answer by writting 'y' for yes or 'n' for no.';;
```suggestion
            * ) echo "  Please answer by writing 'y' for yes or 'n' for no.";;
```

2021-10-05 07:49 UTC, alallema commented on scripts/first-login/000-set-meili-env.sh
> +            * ) echo '  Please answer by writting 'y' for yes or 'n' for no.';;
```suggestion
            * ) echo "  Please answer by writing 'y' for yes or 'n' for no.";;
```

2021-10-05 07:49 UTC, alallema commented on scripts/first-login/000-set-meili-env.sh
> +            * ) echo '  Please answer by writting 'y' for yes or 'n' for no.';
```suggestion
            * ) echo "  Please answer by writing 'y' for yes or 'n' for no.";
```

2021-10-05 07:49 UTC, alallema commented on scripts/first-login/000-set-meili-env.sh
> +            * ) echo '  Please answer by writting 'y' for yes or 'n' for no.';
```suggestion
            * ) echo "  Please answer by writing 'y' for yes or 'n' for no.";
```

2021-10-05 07:49 UTC, alallema commented on scripts/first-login/000-set-meili-env.sh
>      DOMAIN_NAME=""
```suggestion
    DOMAIN_NAME=''
```

2021-10-05 07:49 UTC, alallema commented on scripts/first-login/001-setup-prod.sh
> +    echo "meilisearch-setup"
```suggestion
    echo " meilisearch-setup"
```

2021-10-05 08:01 UTC, viogustian commented
thanks

2021-10-05 09:20 UTC, curquiza commented
Thanks for your changes @viogustian!
I let @alallema do the final review :)

2021-10-05 13:51 UTC, viogustian commented
when will my pull request be merged?

2021-10-05 14:26 UTC, curquiza commented
When she has the time to review, be patient, you can understand we have a lot of work 🙂

2021-10-06 08:40 UTC, alallema approved these changes
LGTM!

2021-10-06 08:43 UTC, merged